### ISSUE TITLE
cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by metalaureate** [mgmtio/phash-image#6]
I had to build pHash 0.9.6 from source because the node docker image is Jessie which has no libphash0-dev package. But when I try to run

`    var phash = require('phash-image');`

I get the error

```module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: libpHash.so.0: cannot open shared object file: No such file or directory
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/src/web/node_modules/phash-image/index.js:3:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

Any thoughts appreciated.

pHash is installed in node-module's parent dir.

**Comment by jonathanong** [comment]
how did you build it from source? i haven't experienced this, though i had to built it from source on my ubuntu 15.04 desktop

**Comment by metalaureate** [comment]
https://github.com/polachok/py-phash/issues/4
